Arithmatic Operation

In [2]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var+3
print(varadd)

[4 5 6 7]


In [11]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1+var2
print(varadd)

[ 6  8 10 12]


In [15]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = np.add(var1,var2)
print(varadd)

[ 6  8 10 12]


In [16]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = np.add(var1,2)
print(varadd)

[3 4 5 6]


In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varsub = var2-var1
print(varsub)

[4 4 4 4]


In [8]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
vardiv = var2//var1
print(vardiv)

[5 3 2 2]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varmult = var1*var2
print(varmult)

[ 5 12 21 32]


In [10]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1%var2
print(varadd)

[1 2 3 4]


In [17]:
x= 3
power = np.power(x,8)
print(f"Power of {x} is {power}")

Power of 3 is 6561


In [18]:
x=5
mod = np.mod(x,2)
print(f"Mod of {x} is {mod}")

Mod of 5 is 1


In [22]:
y=1
reciprocal = np.reciprocal(y)
print(f"Reciprocal of {y} is {reciprocal}")

Reciprocal of 1 is 1


2D array

In [23]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = np.add(var1,var2)
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


In [26]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = np.reciprocal(var1,var2)
print(varadd)

[[1 0 0 0]
 [1 0 0 0]]


In [37]:
arr = np.array([56,4,6,24,32,90])
print(f"min {np.min(arr)} at position {np.argmin(arr)}")
print(f"max {np.max(arr)} at position {np.argmax(arr)}")
print(f"sqrt {np.sqrt(arr)}")

min 4 at position 1
max 90 at position 5
sqrt [7.48331477 2.         2.44948974 4.89897949 5.65685425 9.48683298]


In [35]:
arr = np.array([[1,2,21],[5,32,11]])
print(np.max(arr,axis=0))

[ 5 32 21]


In [40]:
fuc = np.array([1,2,3])
print(np.sin(fuc))
print(np.cos(fuc))
print(np.cumsum(fuc))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
