Array


In [42]:
import numpy as np
x= [1,2,3,4]
y = np.array([1,2,3,4,5])
print(y)
y
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [43]:
l=[]
for i in range(0,4):
    int_1 = int(input("Enter :"))
    l.append(int_1)

print(np.array(l))

Enter : 1
Enter : 23
Enter : 45
Enter : 67


[ 1 23 45 67]


In [48]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(type(arr2))
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [50]:
arr2[0:1,0:]

array([[1, 2, 3, 4]])

In [51]:
arr3 = np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [54]:
arn = np.array([1,2,3,4], ndmin =10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [17]:
import math
print(max(10,20,44,18,97))
print(min(10,20,44,18,97))
print(abs(-15.5))
print(math.sqrt(4))
print(math.factorial(7))
print(math.lcm(5))
print(math.gcd(14))


97
10
15.5
2.0
5040
5
14


In [18]:
import math 
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'sumprod',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [21]:
print(math.perm(2))

2
