DATA TYPES

In [5]:
import numpy as np
var = np.array([1,2,4,5,23,45,11,34])
print("Data types: ",var.dtype)

Data types:  int64


In [6]:
var1 = np.array([1.2,1.45,2.4,67.8])
print("Data type: ",var1.dtype)

Data type:  float64


In [7]:
var2 = np.array(['a','b','c'])
print("Data type: ",var2.dtype)

Data type:  <U1


In [8]:
var3 = np.array(['a','b','c',1,1.2])
print("Data type: ",var3.dtype)

Data type:  <U32


In [12]:
var = np.array([1,2,4,5,23,45,11,34],dtype=np.int8)
print("Data types: ",var.dtype)

Data types:  int8


In [13]:
var = np.array([1,2,4,5,23,45,11,34],dtype='f')
print("Data types: ",var.dtype)
print(var)

Data types:  float32
[ 1.  2.  4.  5. 23. 45. 11. 34.]


In [17]:
x = np.array([1,2,4,5,23,45,11,34])
new = np.float32(x)
new_one = np.int_(new)
print("Data types: ",x.dtype)
print("Data types: ",new.dtype)
print("Data types: ",new_one.dtype)
print(x)
print(new)
print(new_one)

Data types:  int64
Data types:  float32
Data types:  int64
[ 1  2  4  5 23 45 11 34]
[ 1.  2.  4.  5. 23. 45. 11. 34.]
[ 1  2  4  5 23 45 11 34]


In [19]:
x1= np.array([1,2,3,4])
new_1 = x1.astype(float)
print(new_1)

[1. 2. 3. 4.]


SHAPE

In [22]:
var = np.array([[1,2,3],[4,5,6]])
print(var,var.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [25]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1,var1.ndim,var1.shape)

[[[[1 2 3 4]]]] 4 (1, 1, 1, 4)


RESHAPE

In [32]:
var2 = np.array([1,2,3,4,5,6])
print(var2,"\n")
print(var2.ndim,"\n")
var_new = var2.reshape(3,2)
print(var_new)
print(var_new.ndim,"\n")
print(var_new.shape)

[1 2 3 4 5 6] 

1 

[[1 2]
 [3 4]
 [5 6]]
2 

(3, 2)


In [40]:
var3 = np.array([1,2,3,4,5,6,10,12,11,23,13,15])
print(var3,"\n")
print(var3.ndim,"\n")
var_new = var3.reshape(3,2,2)
print(var_new)
print(var_new.ndim,"\n")
print(var_new.shape)

[ 1  2  3  4  5  6 10 12 11 23 13 15] 

1 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [10 12]]

 [[11 23]
  [13 15]]]
3 

(3, 2, 2)


In [41]:
one = var_new.reshape(-1)
print(one,one.ndim)

[ 1  2  3  4  5  6 10 12 11 23 13 15] 1
