Zero


In [2]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones

In [4]:
ar_one = np.ones(4)
ar_one1 = np.ones((6,5))
print(ar_one)
print()
print(ar_one1)



[1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


Range

In [6]:
ar_rn = np.arange(5)
print(ar_rn)

[0 1 2 3 4]


Diagonal

In [7]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


linespace

In [10]:
ar_line = np.linspace(10,20,num=5)
print(ar_line)

[10.  12.5 15.  17.5 20. ]


In [11]:
ar_line = np.linspace(10,20,num=4)
print(ar_line)

[10.         13.33333333 16.66666667 20.        ]


Range