Indexing

In [10]:
import numpy as np
arr = np.array([3,4,5,6])
print(arr[1])
print(arr[-4])

4
3


In [16]:
var2 = np.array([[1,2,3],[4,5,6]])
print(var2)
print(var2.ndim)
print(var2[1,2])
print(var2[1][2])

[[1 2 3]
 [4 5 6]]
2
6
6


In [23]:
var3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(var3)
print(var3.ndim)
print(var3[0,1,2])
print(var3[1,1,-3])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
6
10


Slicing

In [29]:
var1 = np.array([2,3,4,5,6])
print(var1)
print("3 to 5",var1[1:4])
print("3 to end",var1[1:])
print("start to 4",var1[:3])
print(var1[1:5:2])

[2 3 4 5 6]
3 to 5 [3 4 5]
3 to end [3 4 5 6]
start to 4 [2 3 4]
[3 5]


In [35]:
var2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(var2)
print(var2.ndim)
print(var2[1,1])
print(var2[2,1])
print(var2[1:3,0:2])

[[9 8 7]
 [6 5 4]
 [3 2 1]]
2
5
2
[[6 5]
 [3 2]]


In [39]:
var2d = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var2d)
print(var2d.ndim)
print("8 to 5",var2d[1,1:5])
print("5 to 8",var2d[1,4:0:-1])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
2
8 to 5 [8 7 6 5]
5 to 8 [5 6 7 8]


In [44]:
var3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(var3)
print(var3.ndim)
print("2 to 5",var3[0,0:2,1:])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
2 to 5 [[2 3]
 [5 6]]


In [48]:
arr3d = np.random.randint(1,200,(3,5,3))
print(arr3d)
print(arr3d[1,3:,1:])
print(arr3d[:,0:1,0:])

[[[ 10 102 145]
  [130 160   2]
  [177  33 122]
  [183 103  57]
  [ 42  41  40]]

 [[157  18  40]
  [154 141 187]
  [ 65  53 145]
  [177  15  10]
  [128  45  56]]

 [[ 28   8 137]
  [121  79  41]
  [178  45  14]
  [ 51   6 104]
  [139  20  99]]]
[[15 10]
 [45 56]]
[[[ 10 102 145]]

 [[157  18  40]]

 [[ 28   8 137]]]
