Random

In [6]:
import numpy as np
var = np.random.rand(4)#it generate the nuber between 0 and 1
print(var)

[0.70353618 0.63962573 0.6227476  0.5303067 ]


In [5]:
var1 = np.random.rand(2,4)
print(var1)

[[0.70116209 0.02308778 0.87769227 0.63379964]
 [0.75490562 0.22146165 0.52500588 0.52512691]]


randn() generate the random number 0 or greater then 0 it can be positive or nagetive

In [7]:
var2 = np.random.randn(4)
print(var2)

[-1.54262806  0.74528391 -0.9140038   0.31697693]


ranf generate number interval [0.0,1.0) not 1 closer than zero

In [9]:
var3 = np.random.ranf(4)
print(var3)

[0.3181932  0.59241617 0.00468729 0.6408703 ]


randint() it has range defind function

In [13]:
var4 = np.random.randint(10,20,4)
print(var4)

[11 16 17 18]
